#define TERMWIDTH 80
#define TERMHEIGHT 24
#define CWIDTH 9
#define CHEIGHT 10
#define FBWIDTH (TERMWIDTH*CWIDTH)
#define FBHEIGHT (TERMHEIGHT*CHEIGHT)
#define BORDER 5
#define WIDTH  (FBWIDTH + 2*BORDER)
#define HEIGHT (2*FBHEIGHT + 2*BORDER)
